# language: generic  # In case of error: rakefile not found
sudo: require
services:
  - docker

before_install:
  - docker build -t nimiq/docker-react -f ./section7/frontend/Dockerfile.dev ./section7/frontend

script:
  # - docker run nimiq/docker-react npm run test -- --coverage
  - docker run -e CI=true nimiq/docker-react npm run test
