# language: generic  # In case of error: rakefile not found
sudo: require
services:
  - docker

before_install:
  - docker build -t nimiq/docker-react -f ./section7/frontend/Dockerfile.dev ./section7/frontend

script:
  # - docker run nimiq/docker-react npm run test -- --coverage
  - docker run -e CI=true nimiq/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-477353422995"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
