apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: nimiq/multi-client
          # Fix for Skaffold error like:
          # rpc error: code = Unknown desc = Error response from daemon: manifest for nimiq/multi-server:47cdbc606a958b92059529238c01fb9e53694b0e5bc91e31f44d1676900d018d not found
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
