apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      # Volumes allocation.
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          # Volume actual usage.
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              # Dir in the actual host volume where to store files.
              # This is usually not used, we only need it for Postgres.
              subPath: postgres
          env:
            # Read this from a secret object.
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword # Name fo the secret object.
                  key: PGPASSWORD # Key from the key=vaule format.
