apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: nimiq/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      # Mode 2: inject these files in the client container.
      # Note: Mode 1 (not used here) would rebuild the entire container.
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
    - image: nimiq/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
    - image: nimiq/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .

deploy:
  kubectl:
    manifests:
      # Delete these pods when skaffold quits.
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
